version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: myfetus-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"  # (externo 5433 â†’ interno 5432)
    networks:
      - myfetus-net

  backend:
    build:
      context: ./backend
    container_name: myfetus-backend
    depends_on:
      - db
    environment:
      PG_USER: myuser
      PG_PASSWORD: mypassword
      PG_DATABASE: mydatabase
      PG_HOST: myfetus-db     # nome do container do banco (importante!)
      PG_PORT: 5432
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - myfetus-net
    restart: always

volumes:
  db_data:

networks:
  myfetus-net:
    driver: bridge
