version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: myfetus-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - myfetus-net


  backend:
    build:
      context: ./backend
    container_name: myfetus-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_USER: myuser
      PG_PASSWORD: mypassword
      PG_DATABASE: mydatabase
      PG_HOST: myfetus-db
      PG_PORT: 5432
      PORT: 3000
    ports:
      - "3000:3000"
    command: ["node", "server.js"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - myfetus-net
    restart: always


volumes:
  db_data:

networks:
  myfetus-net:
    driver: bridge
